[package]
build = './common/build/build.rs'
description = 'DHT protocol library'
edition = '2018'
name = 'dht'
resolver = '2'
version = '0.5.65'

[workspace]

[dependencies]
async-trait = '0.1'
base64 = '0.13'
failure = '0.1'
hex = '0.4'
log = '0.4'
rand = '0.8'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl', tag = '0.7.71' }
ever-crypto = { git = 'https://github.com/tonlabs/ever-labs-crypto.git', tag = '0.1.18' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
overlay = { git = 'https://github.com/tonlabs/ton-labs-overlay', tag = '0.6.55' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl.git', package = 'ton_api', tag = '0.2.125' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.10.14' }

[dev-dependencies]
external-ip = '4.1'
log4rs = '1.0'
serde_json = '1.0'

[features]
telemetry = [ 'adnl/telemetry', 'overlay/telemetry' ]
